// <auto-generated />
using System;
using AgroGuard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroGuard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroGuardDbContext))]
    partial class AgroGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroGuard.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("IdealNdvi")
                        .HasColumnType("NUMBER(4,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<decimal>("WaterDemandIndex")
                        .HasColumnType("NUMBER(4,3)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AG_CROPS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IdealNdvi = 0.82m,
                            Name = "Soybean",
                            ScientificName = "Glycine max",
                            WaterDemandIndex = 0.78m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IdealNdvi = 0.80m,
                            Name = "Corn",
                            ScientificName = "Zea mays",
                            WaterDemandIndex = 0.84m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IdealNdvi = 0.74m,
                            Name = "Coffee",
                            ScientificName = "Coffea arabica",
                            WaterDemandIndex = 0.66m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IdealNdvi = 0.86m,
                            Name = "Sugarcane",
                            ScientificName = "Saccharum officinarum",
                            WaterDemandIndex = 0.88m
                        });
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<decimal>("TotalAreaHectares")
                        .HasColumnType("NUMBER(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("AG_FARMS", (string)null);
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("AreaHectares")
                        .HasColumnType("NUMBER(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("CropId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("ExpectedHarvestAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmId", "Name")
                        .IsUnique();

                    b.ToTable("AG_FIELDS", (string)null);
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.RiskAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Level")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid?>("SatelliteReadingId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Score")
                        .HasColumnType("NUMBER(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("NVARCHAR2(140)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteReadingId");

                    b.HasIndex("FieldId", "Status", "Level");

                    b.ToTable("AG_RISK_ALERTS", (string)null);
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.SatelliteReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<decimal>("CloudCoveragePercent")
                        .HasColumnType("NUMBER(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Ndvi")
                        .HasColumnType("NUMBER(4,3)");

                    b.Property<decimal>("RainfallMillimeters")
                        .HasColumnType("NUMBER(7,2)");

                    b.Property<decimal>("SoilMoisturePercent")
                        .HasColumnType("NUMBER(5,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<decimal>("SurfaceTemperatureCelsius")
                        .HasColumnType("NUMBER(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "CapturedAt");

                    b.ToTable("AG_SATELLITE_READINGS", (string)null);
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("NVARCHAR2(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("Role")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AG_USERS", (string)null);
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Farm", b =>
                {
                    b.HasOne("AgroGuard.Domain.Entities.User", "Owner")
                        .WithMany("Farms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Field", b =>
                {
                    b.HasOne("AgroGuard.Domain.Entities.Crop", "Crop")
                        .WithMany("Fields")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroGuard.Domain.Entities.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.RiskAlert", b =>
                {
                    b.HasOne("AgroGuard.Domain.Entities.Field", "Field")
                        .WithMany("RiskAlerts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroGuard.Domain.Entities.SatelliteReading", "SatelliteReading")
                        .WithMany()
                        .HasForeignKey("SatelliteReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Field");

                    b.Navigation("SatelliteReading");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.SatelliteReading", b =>
                {
                    b.HasOne("AgroGuard.Domain.Entities.Field", "Field")
                        .WithMany("SatelliteReadings")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Crop", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.Field", b =>
                {
                    b.Navigation("RiskAlerts");

                    b.Navigation("SatelliteReadings");
                });

            modelBuilder.Entity("AgroGuard.Domain.Entities.User", b =>
                {
                    b.Navigation("Farms");
                });
#pragma warning restore 612, 618
        }
    }
}
