-- ==============================================================================
-- GLOBAL SOLUTION - ADVANCED BUSINESS DEVELOPMENT WITH .NET
-- SCRIPT DE CRIAÇÃO DO BANCO DE DADOS ORACLE (DDL)
-- PROJETO: AgroGuard
-- ==============================================================================

-- 1. Remoção das Tabelas Existentes (para permitir reexecução limpa)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AG_RISK_ALERTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AG_SATELLITE_READINGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AG_FIELDS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AG_FARMS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AG_CROPS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AG_USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. Criação das Tabelas

-- Tabela: AG_USERS (Usuários/Produtores)
CREATE TABLE AG_USERS (
    Id RAW(16) NOT NULL,
    Name NVARCHAR2(120) NOT NULL,
    Email NVARCHAR2(180) NOT NULL,
    PasswordHash NVARCHAR2(500) NOT NULL,
    Role NUMBER(10) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT PK_AG_USERS PRIMARY KEY (Id)
);

-- Tabela: AG_CROPS (Culturas de Plantio)
CREATE TABLE AG_CROPS (
    Id RAW(16) NOT NULL,
    Name NVARCHAR2(80) NOT NULL,
    ScientificName NVARCHAR2(120) NOT NULL,
    IdealNdvi NUMBER(4,3) NOT NULL,
    WaterDemandIndex NUMBER(4,3) NOT NULL,
    CONSTRAINT PK_AG_CROPS PRIMARY KEY (Id)
);

-- Tabela: AG_FARMS (Fazendas)
CREATE TABLE AG_FARMS (
    Id RAW(16) NOT NULL,
    OwnerId RAW(16) NOT NULL,
    Name NVARCHAR2(120) NOT NULL,
    City NVARCHAR2(80) NOT NULL,
    State NVARCHAR2(2) NOT NULL,
    Latitude NUMBER(9,6) NOT NULL,
    Longitude NUMBER(9,6) NOT NULL,
    TotalAreaHectares NUMBER(12,2) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT PK_AG_FARMS PRIMARY KEY (Id),
    CONSTRAINT FK_AG_FARMS_AG_USERS_OwnerId FOREIGN KEY (OwnerId) REFERENCES AG_USERS (Id) ON DELETE CASCADE
);

-- Tabela: AG_FIELDS (Talhões/Campos de Plantio)
CREATE TABLE AG_FIELDS (
    Id RAW(16) NOT NULL,
    FarmId RAW(16) NOT NULL,
    CropId RAW(16) NOT NULL,
    Name NVARCHAR2(120) NOT NULL,
    AreaHectares NUMBER(12,2) NOT NULL,
    Latitude NUMBER(9,6) NOT NULL,
    Longitude NUMBER(9,6) NOT NULL,
    SoilType NVARCHAR2(80) NOT NULL,
    PlantedAt TIMESTAMP NOT NULL,
    ExpectedHarvestAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT PK_AG_FIELDS PRIMARY KEY (Id),
    CONSTRAINT FK_AG_FIELDS_AG_CROPS_CropId FOREIGN KEY (CropId) REFERENCES AG_CROPS (Id),
    CONSTRAINT FK_AG_FIELDS_AG_FARMS_FarmId FOREIGN KEY (FarmId) REFERENCES AG_FARMS (Id) ON DELETE CASCADE
);

-- Tabela: AG_SATELLITE_READINGS (Leituras de Satélite)
CREATE TABLE AG_SATELLITE_READINGS (
    Id RAW(16) NOT NULL,
    FieldId RAW(16) NOT NULL,
    CapturedAt TIMESTAMP NOT NULL,
    Source NVARCHAR2(120) NOT NULL,
    Ndvi NUMBER(4,3) NOT NULL,
    SoilMoisturePercent NUMBER(5,2) NOT NULL,
    SurfaceTemperatureCelsius NUMBER(5,2) NOT NULL,
    RainfallMillimeters NUMBER(7,2) NOT NULL,
    CloudCoveragePercent NUMBER(5,2) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT PK_AG_SATELLITE_READINGS PRIMARY KEY (Id),
    CONSTRAINT FK_AG_SATELLITE_READINGS_AG_FIELDS_FieldId FOREIGN KEY (FieldId) REFERENCES AG_FIELDS (Id) ON DELETE CASCADE
);

-- Tabela: AG_RISK_ALERTS (Alertas de Risco)
CREATE TABLE AG_RISK_ALERTS (
    Id RAW(16) NOT NULL,
    FieldId RAW(16) NOT NULL,
    SatelliteReadingId RAW(16) NULL,
    Type NUMBER(10) NOT NULL,
    Level NUMBER(10) NOT NULL,
    Score NUMBER(5,2) NOT NULL,
    Title NVARCHAR2(140) NOT NULL,
    Description NVARCHAR2(500) NOT NULL,
    Recommendation NVARCHAR2(500) NOT NULL,
    Status NUMBER(10) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    ResolvedAt TIMESTAMP NULL,
    CONSTRAINT PK_AG_RISK_ALERTS PRIMARY KEY (Id),
    CONSTRAINT FK_AG_RISK_ALERTS_AG_FIELDS_FieldId FOREIGN KEY (FieldId) REFERENCES AG_FIELDS (Id) ON DELETE CASCADE,
    CONSTRAINT FK_AG_RISK_ALERTS_AG_SATELLITE_READINGS_SatelliteReadingId FOREIGN KEY (SatelliteReadingId) REFERENCES AG_SATELLITE_READINGS (Id) ON DELETE SET NULL
);

-- 3. Criação de Índices Otimizados (conforme Migrations do EF Core)
CREATE UNIQUE INDEX IX_AG_USERS_Email ON AG_USERS (Email);
CREATE UNIQUE INDEX IX_AG_CROPS_Name ON AG_CROPS (Name);
CREATE UNIQUE INDEX IX_AG_FARMS_OwnerId_Name ON AG_FARMS (OwnerId, Name);
CREATE UNIQUE INDEX IX_AG_FIELDS_FarmId_Name ON AG_FIELDS (FarmId, Name);
CREATE INDEX IX_AG_FIELDS_CropId ON AG_FIELDS (CropId);
CREATE INDEX IX_AG_SATELLITE_READINGS_FieldId_CapturedAt ON AG_SATELLITE_READINGS (FieldId, CapturedAt);
CREATE INDEX IX_AG_RISK_ALERTS_FieldId_Status_Level ON AG_RISK_ALERTS (FieldId, Status, Level);
CREATE INDEX IX_AG_RISK_ALERTS_SatelliteReadingId ON AG_RISK_ALERTS (SatelliteReadingId);

-- 4. Inserção de Dados Iniciais (Seed Data)
INSERT INTO AG_CROPS (Id, Name, ScientificName, IdealNdvi, WaterDemandIndex)
VALUES (HEXTORAW('11111111111111111111111111111111'), 'Soybean', 'Glycine max', 0.820, 0.780);

INSERT INTO AG_CROPS (Id, Name, ScientificName, IdealNdvi, WaterDemandIndex)
VALUES (HEXTORAW('22222222222222222222222222222222'), 'Corn', 'Zea mays', 0.800, 0.840);

INSERT INTO AG_CROPS (Id, Name, ScientificName, IdealNdvi, WaterDemandIndex)
VALUES (HEXTORAW('33333333333333333333333333333333'), 'Coffee', 'Coffea arabica', 0.740, 0.660);

INSERT INTO AG_CROPS (Id, Name, ScientificName, IdealNdvi, WaterDemandIndex)
VALUES (HEXTORAW('44444444444444444444444444444444'), 'Sugarcane', 'Saccharum officinarum', 0.860, 0.880);

COMMIT;
